### ISSUE TITLE
iOS - Connect function crashes the app

### ISSUE THREAD

**Issue by nikolip** [alternadom/WiFiFlutter#211]
iOS - 15.2
-- 
wifi_iot: ^0.3.10
--

When calling WifiForIoTPlugin.connect the app crashes to null error. 

Only mandatory argument should be 'ssid', but when not providing "password" or "security" arguments the app crashes to "Could not cast value of type 'NSNull' (0x1dae296c0) to 'NSString' (0x1dae28b18).". 

When debugging with xcode those values comes to connect function as nil. Then when  plugin trying access  them in SwiftWifiIotPlugin  class in lines 126-128 if the value is nil the app crashes.

**Comment by daadu** [comment]
Working on its fix. Thanks for reporting.

**Comment by daadu** [comment]
The PR is under review - meanwhile urge you to test it with following:

```yaml
  wifi_iot: #^0.3.0
    git:
      url: https://github.com/daadu/WiFiFlutter
      path: packages/wifi_iot
      ref: fix-211
```
